Added initial Dockerfile for ECR * aws.yml now checks status of commit is success with Travis CI before pushing * (Hopefully) Travis is configured correctly for both Dockerfile build * traefik.yml and production.py have my temporary domain name * Added Apache 2.0 LICENSE * Made celery beat wait for Django and Postgres to finish migrating all models before-hand.

diff --git a/.github/workflows/aws.yml b/.github/workflows/aws.yml
--- a/.github/workflows/aws.yml
+++ b/.github/workflows/aws.yml
@@ -35,6 +35,22 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+    - name: Check commit status
+      id: commit-status
+      run: |
+        # Check the status of the Git commit
+        CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+        echo "Current status is: $CURRENT_STATUS"
+        while [ "${CURRENT_STATUS^^}" = "PENDING" ];
+          do sleep 10;
+          CURRENT_STATUS=$(curl --url https://api.github.com/repos/${{ github.repository }}/commits/${{ github.sha }}/status --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' | jq -r '.state');
+        done;
+        echo "Current status is: $CURRENT_STATUS"
+        if [ "${CURRENT_STATUS^^}" = "FAILURE" ];
+          then echo "Commit status failed. Canceling execution";
+          exit 1;
+        fi
+
     - name: Checkout
       uses: actions/checkout@v2
 
@@ -67,7 +83,7 @@ jobs:
       id: task-def
       uses: aws-actions/amazon-ecs-render-task-definition@v1
       with:
-        task-definition: task-definition.json
+        task-definition: cookiecutter-django-task-definition.json
         container-name: sample-app
         image: ${{ steps.build-image.outputs.image }}
 
